### ISSUE TITLE
手笔分离作者有没有思路

### ISSUE THREAD

**Issue by tankcong** [GdinKing/HandWrite#2]
手笔分离就是当笔在写的时候忽略手部的多点点击事件。
目前我是通过屏蔽部分区域做的，感觉实现有问题，请教作者有没有什么思路

**Comment by GdinKing** [comment]
> 手笔分离就是当笔在写的时候忽略手部的多点点击事件。
> 目前我是通过屏蔽部分区域做的，感觉实现有问题，请教作者有没有什么思路

目前我这个是支持手笔分离的，判断触摸点的个数，大于1只取第一个有效的，针对电磁屏带笔的还可以判断手写笔的类型是笔还是手指，从而控制什么时候需要响应手指操作，什么时候需要响应笔的书写

**Comment by leiguoqiang1818** [comment]
具体需求能否具体一点



---原始邮件---
发件人: "GdinKing"<notifications@github.com&gt;
发送时间: 2020年11月3日(周二) 上午9:00
收件人: "GdinKing/HandWrite"<HandWrite@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [GdinKing/HandWrite] 手笔分离作者有没有思路 (#2)




 
Closed #2.
